route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: '10.10.87.37:25'
        auth_username: ''
        auth_password: ""
        from: 'svc_xpawamail@vodacom.co.tz'
        to: 'mkippe@credable.io'
